load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_binary")

kt_jvm_binary(
    name = "day23",
    main_class = "day23.Day23Kt",
    srcs = glob(["*.kt"]),
    deps = [
        "//src/main/kotlin/util",
    ],
    resources = [
        "//src/main/resources/day23",
    ],
)
