load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_binary")

kt_jvm_binary(
    name = "day08",
    main_class = "day08.Day08Kt",
    srcs = glob(["*.kt"]),
    deps = [
        "//src/main/kotlin/util",
    ],
    resources = [
        "//src/main/resources/day08",
    ],
)
